packages:
  - "packages/*"

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

overrides:
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.2
